brewery/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from brewery import views

app_name = "brewery"

urlpatterns = [
    path("<slug:brewery_slug>/", views.brewery_index, name="brewery_index"),
    path( "<slug:brewery_slug>/search/", views.brewery_index_search, name="brewery_index_search"),
    # path("<slug:route_slug>/route_descr/", views.route_descr, name="route_descr"),
    # path("<slug:route_slug>/route_city/", views.route_city, name="route_city"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap

from django.views.defaults import permission_denied
from axes.decorators import axes_dispatch

from core.sitemaps import StaticViewSitemap, RouteSitemap, BrewerySitemap

sitemaps = {
    "static": StaticViewSitemap,
    "routes": RouteSitemap,
    "breweries": BrewerySitemap,
}

urlpatterns = [
    path("secret-admin-url/", admin.site.urls),  # Смена стандартного /admin/
    path("admin/", lambda r: permission_denied(r, exception=None)),
    path("secret-admin-url/", axes_dispatch(admin.site.urls)),
    # path("admin/", admin.site.urls),
    path("captcha/", include("captcha.urls")),
    path("", include("main.urls", namespace="main")),
    path("route/", include("route.urls", namespace="route")),
    path("brewery/", include("brewery.urls", namespace="brewery")),
    path("country/", include("country.urls", namespace="country")),
    path("feedback/", include("feedback.urls", namespace="feedback")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),  # для индексации в Яндексе и Google.
]

# Только для разработки (DEBUG=True)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from main import views
from .views import (FeedbackCreateView)

app_name = 'main'


urlpatterns = [
    path("search/", views.index, name="search"),
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("write/", FeedbackCreateView.as_view(), name="feedbackcreateview"),
    path("massage/", views.feedback_massage, name="feedback_massage"),
    path("admin-prelogin/", views.admin_prelogin, name="admin_prelogin"),
    path("admin-redirect/", views.protected_admin_redirect, name="admin_redirect"),
    path("oferta/", views.oferta_view, name="oferta"),
    path("privacy/", views.privacy_view, name="privacy"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

route/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from route import views

app_name = "route"

urlpatterns = [
    path("<slug:route_slug>/", views.route_index, name="route_index"),
    path("<slug:route_slug>/search/", views.route_index_search, name="route_index_search"),
    path("<slug:route_slug>/route_descr/", views.route_descr, name="route_descr"),
    path("<slug:route_slug>/route_city/", views.route_city, name="route_city"),
    path(
        "<slug:route_slug>/route_city/<str:route_base_city>/",
        views.route_city_2,
        name="route_city_2",
    ),
    path(
        "<slug:route_slug>/route_breweries/",
        views.route_breweries,
        name="route_breweries",
    ),
    path(
        "<slug:route_slug>/<slug:brewery_slug>/",
        views.route_brewery,
        name="route_brewery",
    ),
    path("<slug:brewery_slug>/", views.brewery_index, name="brewery_index"),
    path(
        "<slug:route_slug>/route_descr/<slug:brewery_slug>/",
        views.route_descr_brewery,
        name="route_descr_brewery",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brewery/models.py
from django.db import models
from django.urls import reverse
from django.core.paginator import Paginator

from country.models import Сountry
from route.models import Route

class Brewery(models.Model):

    """Модель для создания пивоварен"""

    class Meta:
        db_table = "breweries"
        verbose_name = "Пивоварни"
        verbose_name_plural = "Пивоварни"
        ordering = ["id"]

    title = models.CharField(
        verbose_name="Название пивоварни",
        max_length=100,
        unique=True,
    )
    slug = models.SlugField(
        max_length=100, verbose_name="URL", unique=True, blank=True, null=True
    )
    address = models.CharField(
        max_length=150,
        verbose_name="Адресс",
        blank=True,
        null=True,
    )
    map_link = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="Ссылка на карту",
        null=True,
    )
    working_hours = models.CharField(
        max_length=100,
        verbose_name="Часы работы",
        blank=True,
        null=True,
    )
    sait_link = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="сайт",
        null=True,
    )
    link = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="Ссылка при наведении"
    )
    description = models.TextField(
        max_length=500, blank=True, null=True, verbose_name="Описание пивоварни"
    )
    descript_full = models.TextField(
        max_length=5000, blank=True, null=True, verbose_name="Описание пивоварни полное"
    )
    image1 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image2 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image3 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image4 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image5 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image6 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image7 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image8 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image9 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    image10 = models.ImageField(
        upload_to="brewery_images", blank=True, null=True, default="100.jpeg"
    )
    route_id = models.ForeignKey(
        to=Route,
        on_delete=models.PROTECT,
        verbose_name="Категория-маршрут",
    )
    country_id = models.ForeignKey(
        to=Сountry,
        on_delete=models.PROTECT,
        default=1,
        verbose_name="Категория-страна",
    )

    def get_absolute_url(self):
        return reverse("brewery", kwargs={"brewery_slug": self.slug})

    def __repr__(self):
        return f"<Пивоварня: {self.title}>"

    def __str__(self):
        return f"Пивоварня: {self.title}"


# Create your models here.

brewery/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import context


from brewery.models import Brewery


def brewery_index(request, brewery_slug):

    brewery = Brewery.objects.get(slug=brewery_slug)

    context = {
        "title": "Пивоварня",
        "brewery": brewery,
    }
    return render(request, "brewery/brewery.html", context=context)

def brewery_index_search(request, brewery_slug):

    brewery = Brewery.objects.get(slug=brewery_slug)

    context = {
        "title": "Пивоварня",
        "brewery": brewery,
    }
    return render(request, "brewery/brewery_2.html", context=context)

brewery/templates/brewery/brewery.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
      <section class="breweries">
      {% comment %} <section class="brewery" id="brewery"> {% endcomment %}
        <div class="breadcrumblittle">
          <div class="container-fluid">
            <div class="row">
              <nav class="breadcrumb-arrow" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}">Главная</a></li>
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}#brewery">Пивоварни</a></li>
                  {% comment %} <li class="breadcrumb-item"><a href="{% url "main:index" %}#route">Маршруты</a></li>
                  <li class="breadcrumb-item"><a href="{% url "route:route_index" route.slug %}">Маршрут</a></li>
                  <li class="breadcrumb-item"><a href="{% url "route:route_descr" route.slug %}">Описание маршрута</a></li> {% endcomment %}
                  <li class="breadcrumb-item active" aria-current="page">Описание пивоварни</li>
                </ol>
                <div class="accordion-width">
                  <div class="accordion accordion-flush" id="accordionFlushExample">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed d-block text-center" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                         <h1 class="text-center text-second3"><img class="svg6" src="{{ brewery.image1.url }}" alt="узор"> {{brewery.title}}    <img class="svg3" src="{% static 'img/svg/стрелки/стрелка вниз6.svg' %}" alt="узор"></h1>
                          {% comment %} <img class="svg" src="{% static 'img/svg/Знак 1.svg' %}" alt="узор" width="30" height="30"> {% endcomment %}
                        </button>
                      </h2>
                      <div id="flush-collapseOne" class="accordion-collapse text-center collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body city-desc"><p><big>Адрес пивоварни:</big> <em>{{brewery.address}}</em> <a href="{{brewery.map_link}}" target="_ blank">(показать на карте)</a>. <big>Часы работы:</big>  <em>{{brewery.working_hours}}</em> &nbsp;<big>Сайт пивоварни:</big> <a href="{{brewery.sait_link}}" target="_ blank"> {{brewery.sait_link}}</a>&nbsp; - &nbsp; {{brewery.descript_full | safe}}</p></div>
                      </div>
                    </div>
                  </div>
                </div>
              </nav>
            </div>
          </div>
        </div>
        <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="3000">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5" aria-label="Slide 6"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="6" aria-label="Slide 7"></button>
          </div>
          <div class="carousel-inner my-carousel">
            <div class="carousel-item active">
              <img src="{{ brewery.image2.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image3.url }}" class="d-block mx-auto d-block" alt="...">
              {% if "Brandholz" in brewery.title %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">Winkler Brauerei</p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image4.url }}" class="d-block mx-auto d-block" alt="...">
              {% if "Brandholz" in brewery.title %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">Winkler Brauerei</p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image5.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image6.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image7.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image8.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </section>
      <div class="line" style="border-bottom: solid 5px #8e4c0a;"></div>
    {% endblock content %}

brewery/templates/brewery/brewery_2.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
      <section class="breweries">
      {% comment %} <section class="brewery" id="brewery"> {% endcomment %}
        <div class="breadcrumblittle">
          <div class="container-fluid">
            <div class="row">
              <nav class="breadcrumb-arrow" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'main:search' %}?q={{ request.GET.q|urlencode }}#route">Назад к результатам</a></li>
                  {% comment %} <li class="breadcrumb-item"><a href="{% url "main:index" %}#brewery">Пивоварни</a></li> {% endcomment %}
                  <li class="breadcrumb-item active" aria-current="page">Описание пивоварни</li>
                </ol>
                <div class="accordion-width">
                  <div class="accordion accordion-flush" id="accordionFlushExample">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed d-block text-center" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                         <h1 class="text-center text-second3"><img class="svg6" src="{{ brewery.image1.url }}" alt="узор"> {{brewery.title}}    <img class="svg3" src="{% static 'img/svg/стрелки/стрелка вниз6.svg' %}" alt="узор"></h1>
                          {% comment %} <img class="svg" src="{% static 'img/svg/Знак 1.svg' %}" alt="узор" width="30" height="30"> {% endcomment %}
                        </button>
                      </h2>
                      <div id="flush-collapseOne" class="accordion-collapse text-center collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body city-desc"><p><big>Адрес пивоварни:</big> <em>{{brewery.address}}</em> <a href="{{brewery.map_link}}" target="_ blank">(показать на карте)</a>. <big>Часы работы:</big>  <em>{{brewery.working_hours}}</em> &nbsp;<big>Сайт пивоварни:</big> <a href="{{brewery.sait_link}}" target="_ blank"> {{brewery.sait_link}}</a>&nbsp; - &nbsp; {{brewery.descript_full | safe}}</p></div>
                      </div>
                    </div>
                  </div>
                </div>
              </nav>
            </div>
          </div>
        </div>
        <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="3000">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5" aria-label="Slide 6"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="6" aria-label="Slide 7"></button>
          </div>
          <div class="carousel-inner my-carousel">
            <div class="carousel-item active">
              <img src="{{ brewery.image2.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image3.url }}" class="d-block mx-auto d-block" alt="...">
              {% if "Brandholz" in brewery.title %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">Winkler Brauerei</p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image4.url }}" class="d-block mx-auto d-block" alt="...">
              {% if "Brandholz" in brewery.title %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">Winkler Brauerei</p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image5.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image6.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image7.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image8.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </section>
      <div class="line" style="border-bottom: solid 5px #8e4c0a;"></div>
    {% endblock content %}