core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap

from django.views.defaults import permission_denied
from axes.decorators import axes_dispatch

from core.sitemaps import StaticViewSitemap, RouteSitemap, BrewerySitemap

sitemaps = {
    "static": StaticViewSitemap,
    "routes": RouteSitemap,
    "breweries": BrewerySitemap,
}

urlpatterns = [
    path("secret-admin-url/", admin.site.urls),  # Смена стандартного /admin/
    path("admin/", lambda r: permission_denied(r, exception=None)),
    path("secret-admin-url/", axes_dispatch(admin.site.urls)),
    # path("admin/", admin.site.urls),
    path("captcha/", include("captcha.urls")),
    path("", include("main.urls", namespace="main")),
    path("route/", include("route.urls", namespace="route")),
    path("brewery/", include("brewery.urls", namespace="brewery")),
    path("country/", include("country.urls", namespace="country")),
    path("feedback/", include("feedback.urls", namespace="feedback")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),  # для индексации в Яндексе и Google.
]

# Только для разработки (DEBUG=True)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from main import views
from .views import (FeedbackCreateView)

app_name = 'main'


urlpatterns = [
    path("search/", views.index, name="search"),
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("write/", FeedbackCreateView.as_view(), name="feedbackcreateview"),
    path("massage/", views.feedback_massage, name="feedback_massage"),
    path("admin-prelogin/", views.admin_prelogin, name="admin_prelogin"),
    path("admin-redirect/", views.protected_admin_redirect, name="admin_redirect"),
    path("oferta/", views.oferta_view, name="oferta"),
    path("privacy/", views.privacy_view, name="privacy"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

route/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from route import views

app_name = "route"

urlpatterns = [
    path("<slug:route_slug>/", views.route_index, name="route_index"),
    path("<slug:route_slug>/search/", views.route_index_search, name="route_index_search"),
    path("<slug:route_slug>/route_descr/", views.route_descr, name="route_descr"),
    path("<slug:route_slug>/route_city/", views.route_city, name="route_city"),
    path(
        "<slug:route_slug>/route_city/<str:route_base_city>/",
        views.route_city_2,
        name="route_city_2",
    ),
    path(
        "<slug:route_slug>/route_breweries/",
        views.route_breweries,
        name="route_breweries",
    ),
    path(
        "<slug:route_slug>/<slug:brewery_slug>/",
        views.route_brewery,
        name="route_brewery",
    ),
    path("<slug:brewery_slug>/", views.brewery_index, name="brewery_index"),
    path(
        "<slug:route_slug>/route_descr/<slug:brewery_slug>/",
        views.route_descr_brewery,
        name="route_descr_brewery",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

route/models.py
import uuid
from django.db import models
from django.urls import reverse


def uuid_url():
    return uuid.uuid4()


class Route(models.Model):

    """Модель для создания маршрутов"""

    class Meta:
        db_table = "routes"
        verbose_name = "Маршруты"
        verbose_name_plural = "Маршруты"
        ordering = ("sort_order",)

    name = models.CharField(
        verbose_name="Название маршрута",
        max_length=100,
        unique=True,
        error_messages={"unique": "такой маршрут уже существует"},
    )
    slug = models.SlugField(
        max_length=110, verbose_name="URL", unique=True, blank=True, null=True
    )
    base_city = models.CharField(max_length=50, verbose_name="Базовый город")
    base_city_2 = models.CharField(
        max_length=50, verbose_name="Базовый город 2", blank=True, null=True
    )
    city_slug = models.SlugField(
        max_length=110, verbose_name="URL_city", blank=True, null=True
    )
    base_city_3 = models.CharField(
        max_length=50, verbose_name="Базовый город 3", blank=True, null=True
    )
    city_desc = models.TextField(
        max_length=10000, blank=True, null=True, verbose_name="Описание города"
    )
    city_desc_2 = models.TextField(
        max_length=10000, blank=True, null=True, verbose_name="Описание города 2"
    )
    route_desc = models.TextField(
        max_length=50000, blank=True, null=True, verbose_name="Описание маршрута"
    )
    link = models.CharField(
        max_length=1000, blank=True, null=True, verbose_name="Ссылка при наведении"
    )
    image_route1 = models.ImageField(
        upload_to="route_images/route",
        blank=True,
        null=True,
    )
    image_route2 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route3 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route4 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route5 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route6 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route7 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route8 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route9 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route10 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route11 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route12 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route13 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route14 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route15 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_route16 = models.ImageField(
        upload_to="route_images/route", blank=True, null=True, default="100.jpeg"
    )
    image_city1 = models.ImageField(
        upload_to="route_images/city",
        blank=True,
        null=True,
        default="route_images/city/100.jpeg",
    )
    image_city2 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city3 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city4 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city5 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city6 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city7 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city8 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city9 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city10 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city11 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    image_city12 = models.ImageField(
        upload_to="route_images/city", blank=True, null=True, default="100.jpeg"
    )
    sort_order = models.IntegerField(
        "Порядок сортировки",
        blank=True,
        null=True,
        default=None,
        db_index=True,  # Для ускорения сортировки
    )

    def get_absolute_url(self):
        return reverse("route:route_index", kwargs={"route_slug": self.slug})

    def __repr__(self):
        return f"<{self.name}>"

    def __str__(self):
        return f"{self.name}"

route/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import Template, Context


from brewery.models import Brewery
from route.models import Route


def route_index(request, route_slug):

    routes = Route.objects.all()
    route = Route.objects.get(slug=route_slug)

    # Сохраняем slug текущего маршрута в сессии
    request.session["last_route_slug"] = route_slug

    route_dark = range(1, 6)
    route_light = range(6, 70)
    route_disabled = range(70, 100)

    context = {
        "title": "Маршрут",
        "routes": routes,
        "route": route,
        "route_dark": route_dark,
        "route_light": route_light,
        "route_disabled": route_disabled,
    }
    return render(request, "route/route.html", context=context)


def route_index_search(request, route_slug):

    routes = Route.objects.all()

    route = Route.objects.get(slug=route_slug)

    route_dark = range(1, 6)
    route_light = range(6, 70)
    route_disabled = range(70, 100)

    context = {
        "title": "Маршрут",
        "routes": routes,
        "route": route,
        "route_dark": route_dark,
        "route_light": route_light,
        "route_disabled": route_disabled,
    }
    return render(request, "route/route_2.html", context=context)


def route_descr(request, route_slug):
    route = Route.objects.get(slug=route_slug)
    breweries = route.brewery_set.all()  #  связанные пивоварни

    # Создаём шаблон из строки в БД и рендерим его с контекстом
    template_from_db = Template(route.route_desc)
    rendered_description = template_from_db.render(
        Context(
            {
                "route": route,
                "breweries": breweries,
            }
        )
    )

    context = {
        "title": "Описание маршрута",
        "route": route,
        "breweries": breweries,
        "rendered_description": rendered_description,  # Передаём обработанный HTML в наш route-description.html
    }

    return render(request, "route/route-description.html", context=context)


def route_city(request, route_slug):

    route = Route.objects.get(slug=route_slug)

    context = {
        "title": "Базовый город",
        "route": route,
    }
    return render(request, "route/route-base-city.html", context=context)


def route_city_2(request, route_slug, route_base_city):

    route = Route.objects.get(slug=route_slug)
    # route_base_city =route.base_city

    context = {
        "title": "Второй базовый город",
        "route": route,
    }
    return render(request, "route/route-base-city_2.html", context=context)


def route_breweries(request, route_slug):

    route = Route.objects.get(slug=route_slug)

    context = {
        "title": "Пивоварни на маршруте",
        "route": route,
        "breweries": route.brewery_set.all(),
    }
    return render(request, "route/route-breweries.html", context=context)


def route_brewery(request, route_slug, brewery_slug):

    route = Route.objects.get(slug=route_slug)
    brewery = Brewery.objects.get(slug=brewery_slug)

    context = {
        "title": "Пивоварня",
        "route": route,
        "brewery": brewery,
        # "breweries": route.brewery_set.all(),
    }
    return render(request, "route/route-brewery.html", context=context)


def route_descr_brewery(request, route_slug, brewery_slug):

    route = Route.objects.get(slug=route_slug)
    brewery = Brewery.objects.get(slug=brewery_slug)

    context = {
        "title": "Пивоварня",
        "route": route,
        "brewery": brewery,
        # "breweries": route.brewery_set.all(),
    }
    return render(request, "route/route-descr-brewery.html", context=context)


def brewery_index(request, brewery_slug):

    brewery = Brewery.objects.get(slug=brewery_slug)

    context = {
        "title": "Пивоварня",
        "brewery": brewery,
    }
    return render(request, "brewery/brewery.html", context=context)

route/templates/route/route-base-city_2.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
      <section class="route2" id="route2">
        <!-- <div class="breadcrumbmiddle">
          <div class="container-fluid">
            <div class="row">
              <nav class="breadcrumb-arrow" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="./index.html#main">Главная</a></li>
                  <li class="breadcrumb-item"><a href="./index.html#route">Маршруты</a></li>
                  <li class="breadcrumb-item"><a href="./route.html">Маршрут</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Базовый город</li>
                  <li>
                  </li>
                  <div class="center div-width">
                    <h1 class="text-second3"><img class="svg2" src="img/svg/орнамент-обрезан.svg" alt="узор"> Ауфзес <img class="svg2" src="img/svg/орнамент правый обрезан.svg" alt="узор"></h1>
                  </div>
                </ol>
              </nav>
            </div>
          </div>
        </div> -->
        <div class="breadcrumblittle">
          <div class="container-fluid">
            <div class="row">
              <nav class="breadcrumb-arrow" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}">Главная</a></li>
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}#route">Маршруты</a></li>
                  <li class="breadcrumb-item"><a href="{% url "route:route_index" route.slug %}">Маршрут</a></li>
                  <li class="breadcrumb-item"><a href="{% url "route:route_city" route.slug %}">Базовый город</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Второй базовый город</li>
                </ol>
              </nav>
              <div class="accordion-width">
                <div class="accordion accordion-flush" id="accordionFlushExample">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                      <button class="accordion-button collapsed d-block text-center" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        <h1 class="text-center text-second3 ms-5"><img class="svg5" src="{% static 'img/svg/castle.svg' %}" alt="узор">
                          {{route.base_city_2 }}
                            {% if route.base_city_3 %} / {% endif %}
                          {{route.base_city_3 |default_if_none:" "}}
                        <img class="svg5" src="{% static 'img/svg/castle.svg' %}" alt="узор">   <img class="svg3" src="{% static 'img/svg/стрелки/стрелка вниз6.svg' %}" alt="узор"></h1>
                      </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse text-center collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                      <div class="accordion-body"><p class="city-desc">{{route.city_desc_2 | safe }}</a></p></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="carouselExampleCaptions1" class="carousel slide carousel-fade">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide-to="4" aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide-to="5" aria-label="Slide 6"></button>
          </div>
          <div class="carousel-inner my-carousel">
            <div class="carousel-item active">
              {% if route.image_city7 %}
              <img src="{{ route.image_city7.url }}" class="d-block mx-auto d-block" alt="...">
              {% endif %}
              {% if route.base_city_3 %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">{{route.base_city_2}} </p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              {% if route.image_city8 %}
              <img src="{{ route.image_city8.url }}" class="d-block mx-auto d-block" alt="...">
              {% endif %}
              {% if route.base_city_3 %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">{{route.base_city_2}} </p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              {% if route.image_city9 %}
              <img src="{{ route.image_city9.url }}" class="d-block mx-auto d-block" alt="...">
              {% endif %}
              {% if route.base_city_3 %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">{{route.base_city_2}} </p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              {% if route.image_city10 %}
              <img src="{{ route.image_city10.url }}" class="d-block mx-auto d-block" alt="...">
              {% endif %}
              {% if route.base_city_3 %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">{{route.base_city_2}} </p>
              </div>>
              {% endif %}
            </div>
            <div class="carousel-item">
              {% if route.image_city11 %}
              <img src="{{ route.image_city11.url }}" class="d-block mx-auto d-block" alt="...">
              {% endif %}
              {% if route.base_city_3 %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">{{route.base_city_3}} </p>
              </div>
              {% endif %}
            </div>
            <div class="carousel-item">
              {% if route.image_city12 %}
              <img src="{{ route.image_city12.url }}" class="d-block mx-auto d-block" alt="...">
              {% endif %}
              {% if route.base_city_3 %}
              <div class="carousel-caption d-flex flex-column align-items-center">
                <p class="bg-dark bg-opacity-10 py-1 px-3">{{route.base_city_3}} </p>
              </div>
              {% endif %}
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions1" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <!-- <div class="container-fluid p-0 m-0">
          <div class="row">
            <div class="col">
            </div>
            <div class="text-little col-9">
              <h3 class="text-third4">Ауфзес — маленький городок в Баварии, в знаменитой области Франкония, которая славится своими красивыми пейзажами и традиционной культурой. Это идеальное место для тех, кто хочет насладиться тихой и спокойной атмосферой, насыщенной историей и красивыми видами. Имеется исторический замок Ауфзес, построенный в 14 веке</h3>
            </div>
            <div class="col">
            </div>
          </div>
        </div> -->
      </section>
      <div class="line" style="border-bottom: solid 5px #8e4c0a;"></div>
{% endblock content %}

route/templates/route/route-breweries.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
      <section class="route2" id="route2">
        <div class="breadcrumblittle">
          <div class="container-fluid">
            {% comment %} <div class="row"> {% endcomment %}
              <nav class="breadcrumb-arrow" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}">Главная</a></li>
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}#route">Маршруты</a></li>
                  <li class="breadcrumb-item"><a href="{% url "route:route_index" route.slug %}">Маршрут</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Пивоварни на маршруте</li>
                  {% comment %} <li class="breadcrumb-item active" aria-current="page">Описание пивоварни</li> {% endcomment %}
                </ol>
              </nav>

              <div class="col-12">
                <h1 class="text-center text-second3" style="line-height: 50px;"><img class="svg" src="{% static "img/svg/1-3.svg" %}" alt="узор" width="60" height="40"> {{route.name}} <img class="svg" src="{% static "./img/svg/1-4.svg" %}" alt="узор" width="60" height="40"></h1>
              </div>
              <div class="col-12">
                <h2 class="text-center text-second4 mb-5" style="line-height: 30px;"><img class="svg" src="{% static 'img/svg/круг/обруч.svg' %}" alt="узор" width="12" height="12"> Пивоварни на маршруте <img class="svg" src="{% static 'img/svg/круг/обруч.svg' %}" alt="узор" width="12" height="12"></h2>
              </div>

              {% for brewery in breweries %}
              <div class="container2">
                <div class= "container2 col-2 col-sm-2 col-md-3 col-lg-4 col-xl-4">
                  <p id="image12"><a href="{% url "route:route_brewery" route.slug brewery.slug %}"><img id="image13" src="{{ brewery.image1.url }}" alt="пивоварня"></a></p>
                  <p id="image_text12"><h4><a href="{% url "route:route_brewery" route.slug brewery.slug %}" class="route-name color1" data-bs-toggle="tooltip" data-bs-placement="top" title="{{brewery.description}}">{{brewery.title}}</a></h4></p>
                </div>
              </div>
              {% endfor %}

            {% comment %} </div> {% endcomment %}
          </div>
        </div>
      </section>
      <div class="line" style="border-bottom: solid 5px #8e4c0a;"></div>
    {% endblock content %}

route/templates/route/route-brewery.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
      <section class="breweries">
        <div class="breadcrumblittle">
          <div class="container-fluid">
            <div class="row">
              <nav class="breadcrumb-arrow" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}">Главная</a></li>
                  <li class="breadcrumb-item"><a href="{% url "main:index" %}#route">Маршруты</a></li>
                  <li class="breadcrumb-item"><a href="{% url "route:route_index" route.slug %}">Маршрут</a></li>
                  <li class="breadcrumb-item"><a href="{% url "route:route_breweries" route.slug %}">Пивоварни на маршруте</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Описание пивоварни {{brewery.title}}</li>
                </ol>
                <div class="accordion-width">
                  <div class="accordion accordion-flush" id="accordionFlushExample">
                    <div class="accordion-item">
                      <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed d-block text-center" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                          <h1 class="text-center text-second3"><img class="svg6" src="{{ brewery.image1.url }}" alt="узор"> {{brewery.title}}    <img class="svg3" src="{% static 'img/svg/стрелки/стрелка вниз6.svg' %}" alt="узор"></h1>
                          {% comment %} <img class="svg" src="{% static 'img/svg/Знак 1.svg' %}" alt="узор" width="30" height="30"> {% endcomment %}
                        </button>
                      </h2>
                      <div id="flush-collapseOne" class="accordion-collapse text-center collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                      <div class="accordion-body city-desc"><p><big>Адрес пивоварни:</big> <em>{{brewery.address}}</em> <a href="{{brewery.map_link}}" target="_ blank">(показать на карте)</a>. <big>Часы работы:</big>  <em>{{brewery.working_hours}}</em> <big>Сайт пивоварни:</big> <a href="{{brewery.sait_link}}" target="_ blank"> {{brewery.sait_link}}</a>&nbsp; - &nbsp;{{brewery.descript_full | safe}}</p></div>
                      </div>
                    </div>
                  </div>
                </div>
              </nav>
            </div>
          </div>
        </div>
        <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="3000">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5" aria-label="Slide 6"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="6" aria-label="Slide 7"></button>
          </div>
          <div class="carousel-inner my-carousel">
            <div class="carousel-item active">
              <img src="{{ brewery.image2.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image3.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image4.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image5.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image6.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image7.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{ brewery.image8.url }}" class="d-block mx-auto d-block" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </section>
      <div class="line" style="border-bottom: solid 5px #8e4c0a;"></div>
    {% endblock content %}