core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap

from django.views.defaults import permission_denied
from axes.decorators import axes_dispatch

from core.sitemaps import StaticViewSitemap, RouteSitemap, BrewerySitemap

sitemaps = {
    "static": StaticViewSitemap,
    "routes": RouteSitemap,
    "breweries": BrewerySitemap,
}

urlpatterns = [
    path("secret-admin-url/", admin.site.urls),  # Смена стандартного /admin/
    path("admin/", lambda r: permission_denied(r, exception=None)),
    path("secret-admin-url/", axes_dispatch(admin.site.urls)),
    # path("admin/", admin.site.urls),
    path("captcha/", include("captcha.urls")),
    path("", include("main.urls", namespace="main")),
    path("route/", include("route.urls", namespace="route")),
    path("brewery/", include("brewery.urls", namespace="brewery")),
    path("country/", include("country.urls", namespace="country")),
    path("feedback/", include("feedback.urls", namespace="feedback")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),  # для индексации в Яндексе и Google.
]

# Только для разработки (DEBUG=True)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

feedback/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import (FeedbackCreateView,)
from feedback import views

app_name = "feedback"

urlpatterns = [
    path("", FeedbackCreateView.as_view(), name="feedbackcreateview"),
    path("massage/", views.feedback_massage, name="feedback_massage"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from main import views
from .views import (FeedbackCreateView)

app_name = 'main'


urlpatterns = [
    path("search/", views.index, name="search"),
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("write/", FeedbackCreateView.as_view(), name="feedbackcreateview"),
    path("massage/", views.feedback_massage, name="feedback_massage"),
    path("admin-prelogin/", views.admin_prelogin, name="admin_prelogin"),
    path("admin-redirect/", views.protected_admin_redirect, name="admin_redirect"),
    path("oferta/", views.oferta_view, name="oferta"),
    path("privacy/", views.privacy_view, name="privacy"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

route/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from route import views

app_name = "route"

urlpatterns = [
    path("<slug:route_slug>/", views.route_index, name="route_index"),
    path("<slug:route_slug>/search/", views.route_index_search, name="route_index_search"),
    path("<slug:route_slug>/route_descr/", views.route_descr, name="route_descr"),
    path("<slug:route_slug>/route_city/", views.route_city, name="route_city"),
    path(
        "<slug:route_slug>/route_city/<str:route_base_city>/",
        views.route_city_2,
        name="route_city_2",
    ),
    path(
        "<slug:route_slug>/route_breweries/",
        views.route_breweries,
        name="route_breweries",
    ),
    path(
        "<slug:route_slug>/<slug:brewery_slug>/",
        views.route_brewery,
        name="route_brewery",
    ),
    path("<slug:brewery_slug>/", views.brewery_index, name="brewery_index"),
    path(
        "<slug:route_slug>/route_descr/<slug:brewery_slug>/",
        views.route_descr_brewery,
        name="route_descr_brewery",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/models.py
from django.db import models
from django.contrib.auth.models import User


class Feedback(models.Model):

    """ Модель обратной связи"""
 
    class Meta:
        db_table = "app_feedback"
        verbose_name = "Обратная связь"
        verbose_name_plural = "Обратная связь"
        ordering = ["-time_create"]

    subject = models.CharField(max_length=255, verbose_name="Тема письма")
    email = models.EmailField(max_length=255, verbose_name="Электронный адрес (email)")
    content = models.TextField(verbose_name="Содержимое письма")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")
    ip_address = models.GenericIPAddressField(
        verbose_name="IP отправителя", blank=True, null=True
    )
    user = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"Вам письмо от {self.email}"

feedback/forms.py
from django import forms
from captcha.fields import CaptchaField
# from django.conf import settings
# from django_recaptcha.fields import ReCaptchaField
# from django_recaptcha.widgets import ReCaptchaV2Checkbox
from .models import Feedback


class FeedbackCreateForm(forms.ModelForm):
    """Форма отправки обратной связи"""
    # Поле капчи
    captcha = CaptchaField(
        label="Введите текст с картинки (можно строчными буквами), для обновления текста перезагрузите страницу",
        error_messages={
            "invalid": "Введен неправильный текст с картинки",
            "required": "Пожалуйста, введите текст с картинки",
        },
    )
    # recaptcha = ReCaptchaField(
    #     widget=ReCaptchaV2Checkbox,
    #     public_key=settings.RECAPTCHA_PUBLIC_KEY,
    #     private_key=settings.RECAPTCHA_PRIVATE_KEY,
    #     label="ReCAPTCHA",
    # )

    agree_to_terms = forms.BooleanField(
        required=True,
        label="Я согласен с политикой конфиденциальности и договором-офертой",
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
        error_messages={"required": "Необходимо принять условия соглашения"},
    )

    class Meta:
        model = Feedback
        fields = ("subject", "email", "content", "captcha", "agree_to_terms")
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "Текст сообщения",
                    "rows": 3,
                    "class": "form-control",
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы"""
        super().__init__(*args, **kwargs)

        # Стили для всех полей
        for field in self.fields:
            if field != "agree_to_terms":
                self.fields[field].widget.attrs.update(
                    {"class": "form-control", "autocomplete": "off"}
                )

        # Кастомные placeholder
        self.fields["subject"].widget.attrs["placeholder"] = "Тема сообщения"
        self.fields["email"].widget.attrs["placeholder"] = "Ваш email"

feedback/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import context

from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import FeedbackCreateForm
from .models import Feedback
from .email import send_contact_email_message
from .utils import get_client_ip


class FeedbackCreateView(SuccessMessageMixin, CreateView):
    model = Feedback
    form_class = FeedbackCreateForm
    success_message = "Ваше письмо успешно отправлено администрации сайта"
    template_name = "feedback/feedback.html"
    extra_context = {"title": "Контактная форма"}
    success_url = reverse_lazy("feedback:feedback_massage")


    def form_valid(self, form):
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.ip_address = get_client_ip(self.request)
            if self.request.user.is_authenticated:
                feedback.user = self.request.user
            send_contact_email_message(
                feedback.subject,
                feedback.email,
                feedback.content,
                feedback.ip_address,
                feedback.user_id,
            )
        return super().form_valid(form)


def feedback_massage(request):
    context = {
        "title": "Успешная отправка",
        }
    return render(request, "feedback/feedback_massage.html", context=context)

feedback/templates/feedback/feedback.html

{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <section class="write" id="write" style="height: 850px;">
      <div class="card mx-auto border-0 col-6 col-sm-6 col-md-8 col-lg-8 col-xl-6 w-50" style="background: #edb176;">
        <div class="card-body" style="color: #955515; text-shadow: none; font-weight: 500; font-size: 16px;">
            <div class="card-title">
                <h4 style="color: #855526;">Контактная форма</h4>
                <p>Пивоваренный маршрут находится в ограниченном доступе. Для получения детальной информации по интересующему маршруту, отправьте сообщение с его названием и другой нужной информацией администратору сайта.</p>
            </div>
            <form method="post" action="{% url 'feedback:feedbackcreateview' %}">
                {% csrf_token %}

                <!-- Рендерим полей, кроме чекбокса и капчи -->
                {% for field in form %}
                    {% if field.name != 'captcha' and field.name != 'agree_to_terms' %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
                                <!-- Капча с обработкой ошибок -->
                <div class="mb-3">
                    <label for="{{ form.captcha.id_for_label }}" class="form-label1">
                        {{ form.captcha.label }}
                    </label>
                    {{ form.captcha }}
                    {% if form.captcha.errors %}
                        <div class="alert alert-danger mt-1">
                            {% for error in form.captcha.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% comment %} <small class="form-text text-muted">Для обновления капчи перезагрузите страницу</small> {% endcomment %}
                </div>

                <!-- Чекбокс согласия -->
                <div class="form-check mb-3">
                    {{ form.agree_to_terms }}
                    <label for="{{ form.agree_to_terms.id_for_label }}" class="form-check-label">
                        Я согласен с<a href="{% url 'main:privacy' %}" target="_blank">политикой конфиденциальности</a>и<a href="{% url 'main:oferta' %}" target="_blank">договором-офертой</a>
                    </label>
                </div>

                <!-- Кнопки -->
                <div class="d-grid gap-2 d-md-block mt-2 me-2">
                    <button type="submit" class="button-input">Отправить письмо</button>
                    <button type="button" class="button-delete" onclick="window.history.back()">Отмена</button>
                </div>
            </form>
        </div>
      </div>
    </section>
{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <!-- Подключение шрифтовых иконок, можно получить на fontawesome.com -->
    <script src="https://kit.fontawesome.com/fce9a50d02.js" crossorigin="anonymous"></script>
  </body>
</html>

feedback/templates/feedback/feedback_email_send.html
{% autoescape off %}

Здравствуйте, Администратор,

С контактной формы поступило новое сообщение со следующим содержимым:

    {{ content }}

    IP Адрес отправителя: {{ ip }}
    Email отправителя: {{ email }}
    {% if user %}Пользователь: {{ user.username }}{% endif %}

Команда сайта Django Base Project

{% endautoescape %}

feedback/templates/feedback/feedback_massage.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<section class="write1">
  <div style="max-width: 100%; min-height: 50px;"></div>
  <div class="mx-auto col-6 col-sm-6 col-md-8 col-lg-8 col-xl-6 w-50 rounded-sm" style="background: #edb176; border-radius: 10px;">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li class="{{ message.tags }}"><i class="icon-{{ message.tags }}"></i> {{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="d-grid gap-2 col-6 mx-auto">
        {% comment %} <button type="button" class="button-input my-3" onclick="history.go(-2)">Назад</button> {% endcomment %}
        <a href="{% url 'route:route_index' route_slug=request.session.last_route_slug %}" class="button-input my-3 text-center">Назад к маршруту</a>
    </div>
  </div>
  </div>
</section>
{% endblock %}